"""Add Hinge-style prompts and preferences

Revision ID: 11efbc24f179
Revises: 4a06a7607b64
Create Date: 2026-02-04 21:10:16.493940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11efbc24f179'
down_revision: Union[str, None] = '4a06a7607b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_interests_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_interests_user_id'), ['user_id'], unique=False)

    op.create_table('user_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_photos_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_dealbreaker', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('user_prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False, comment='The prompt question text'),
    sa.Column('answer', sa.Text(), nullable=False, comment="User's text answer"),
    sa.Column('type', sa.String(length=20), nullable=False, comment='text, audio, image'),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_prompts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('gift_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_gift_tx_receiver_unread', ['receiver_id', 'is_read'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_match_created', ['match_id', 'created_at'], unique=False)

    with op.batch_alter_table('swipes', schema=None) as batch_op:
        batch_op.create_index('idx_swipes_to_action', ['to_user_id', 'action'], unique=False)
        batch_op.create_unique_constraint('uq_swipe_from_to', ['from_user_id', 'to_user_id'])

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True, comment='When the user was last online'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.drop_column('is_internal')

    with op.batch_alter_table('swipes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_swipe_from_to', type_='unique')
        batch_op.drop_index('idx_swipes_to_action')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_match_created')

    with op.batch_alter_table('gift_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_gift_tx_receiver_unread')

    with op.batch_alter_table('user_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prompts_user_id'))

    op.drop_table('user_prompts')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_photos_user_id'))

    op.drop_table('user_photos')
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_interests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_interests_tag'))

    op.drop_table('user_interests')
    # ### end Alembic commands ###
