"""Add monetization models

Revision ID: 172dcbf0aea7
Revises: 7925103b2039
Create Date: 2026-01-10 12:32:35.112097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172dcbf0aea7'
down_revision: Union[str, None] = '7925103b2039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentage commission'),
    sa.Column('commission_type', sa.String(length=20), nullable=False, comment='percentage, fixed'),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('total_conversions', sa.Integer(), nullable=False),
    sa.Column('total_revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_commission_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pricing_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False, comment='Array of price variants with name, price, features'),
    sa.Column('target_segment', sa.String(length=50), nullable=False),
    sa.Column('traffic_split', sa.JSON(), nullable=False, comment='Percentage split for each variant'),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft, running, completed, cancelled'),
    sa.Column('results', sa.JSON(), nullable=False, comment='Metrics for each variant: conversions, revenue, rate'),
    sa.Column('winner_variant', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('applicable_plans', sa.JSON(), nullable=False),
    sa.Column('target_segments', sa.JSON(), nullable=False),
    sa.Column('first_purchase_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)

    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('unlimited_swipes', sa.Boolean(), nullable=False),
    sa.Column('see_who_likes_you', sa.Boolean(), nullable=False),
    sa.Column('boosts_per_month', sa.Integer(), nullable=False),
    sa.Column('super_likes_per_day', sa.Integer(), nullable=False),
    sa.Column('rewind_unlimited', sa.Boolean(), nullable=False),
    sa.Column('incognito_mode', sa.Boolean(), nullable=False),
    sa.Column('advanced_filters', sa.Boolean(), nullable=False),
    sa.Column('priority_listing', sa.Boolean(), nullable=False),
    sa.Column('message_before_match', sa.Boolean(), nullable=False),
    sa.Column('read_receipts', sa.Boolean(), nullable=False),
    sa.Column('profile_boost', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('revenue_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False, comment='subscription, boost, superlike, gift, feature'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway', sa.String(length=30), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('promo_code_id', sa.Uuid(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acquisition_channel', sa.String(length=50), nullable=True),
    sa.Column('affiliate_id', sa.String(length=50), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revenue_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('boost_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('boost_type', sa.String(length=30), nullable=False, comment='standard, super, mega'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('views_during_boost', sa.Integer(), nullable=False),
    sa.Column('likes_during_boost', sa.Integer(), nullable=False),
    sa.Column('matches_during_boost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['revenue_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_gateway_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='payment_initiated, payment_completed, payment_failed, refund, etc.'),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['revenue_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_gateway_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_gateway_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_gateway_logs_gateway'), ['gateway'], unique=False)

    op.create_table('promo_redemptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('promo_code_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['revenue_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('gateway_refund_id', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['revenue_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superlike_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False, comment='subscription, purchase'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['revenue_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superlike_purchases')
    op.drop_table('refunds')
    op.drop_table('promo_redemptions')
    with op.batch_alter_table('payment_gateway_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_gateway_logs_gateway'))
        batch_op.drop_index(batch_op.f('ix_payment_gateway_logs_created_at'))

    op.drop_table('payment_gateway_logs')
    op.drop_table('boost_purchases')
    with op.batch_alter_table('revenue_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_revenue_transactions_created_at'))

    op.drop_table('revenue_transactions')
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_user_id'))

    op.drop_table('user_subscriptions')
    op.drop_table('subscription_plans')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    op.drop_table('pricing_tests')
    op.drop_table('affiliate_partners')
    # ### end Alembic commands ###
