"""add_performance_indexes_and_infra

Revision ID: 4a06a7607b64
Revises: 5d157be5f6b3
Create Date: 2026-01-16 22:55:47.588967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a06a7607b64'
down_revision: Union[str, None] = '5d157be5f6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_conversions', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('backup_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('checksum', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('triggered_by', sa.Uuid(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('retention_cohorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculated_at', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_retention_cohorts_cohort_date')
        batch_op.create_index(batch_op.f('ix_retention_cohorts_cohort_date'), ['cohort_date'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_active_created', ['is_active', 'created_at'], unique=False)
        batch_op.create_index('idx_users_gender_age', ['gender', 'age'], unique=False)
        batch_op.create_index('idx_users_lat_lon', ['latitude', 'longitude'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_lat_lon')
        batch_op.drop_index('idx_users_gender_age')
        batch_op.drop_index('idx_users_active_created')

    with op.batch_alter_table('retention_cohorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_cohorts_cohort_date'))
        batch_op.create_index('ix_retention_cohorts_cohort_date', ['cohort_date'], unique=False)
        batch_op.drop_column('calculated_at')

    with op.batch_alter_table('backup_status', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('triggered_by')
        batch_op.drop_column('checksum')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_size')
        batch_op.drop_column('backup_type')

    op.drop_table('acquisition_channels')
    # ### end Alembic commands ###
