"""expand_report_model

Revision ID: 5d157be5f6b3
Revises: 90417fd82de9
Create Date: 2026-01-15 22:51:53.940562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5d157be5f6b3'
down_revision: Union[str, None] = '1aac292cdf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # These tables already exist in the DB but were not in alembic history
    # op.create_table('user_interests', ...)
    # op.create_table('user_photos', ...)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_urls', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('admin_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('resolution', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_reports_admin_id_users', 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photos')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('photos', sa.JSON(), nullable=False))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_admin_id_users', type_='foreignkey')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolution')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('evidence_urls')

    # op.drop_table('user_photos')
    # op.drop_table('user_interests')
    # ### end Alembic commands ###
