"""sync_user_schema

Revision ID: 84c234c1a660
Revises: f1a2b3c4d5e7
Create Date: 2026-01-11 11:00:47.304847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c234c1a660'
down_revision: Union[str, None] = 'f1a2b3c4d5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_foreign_key('fk_messages_receiver_id', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_receiver_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_column('photo_url')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
