"""add_telegram_charge_id

Revision ID: 97dc34be6cab
Revises: 50f68ebfca2c
Create Date: 2026-01-11 21:31:34.670909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dc34be6cab'
down_revision: Union[str, None] = '50f68ebfca2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual SQLite-compatible migration avoiding Batch Mode circular dependency
    # Note: We relax constraints (nullable=True) and skip FKs for SQLite stability
    
    # Messages
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False, server_default='false'))
        # Skipping FK creation to avoid recreation issues
        # batch_op.create_foreign_key('fk_messages_receiver_id_users', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')

    # Revenue
    with op.batch_alter_table('revenue_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_charge_id', sa.String(length=100), nullable=True, comment='Explicit Telegram payment charge ID'))

    # Users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0', comment="User's Telegram Stars balance"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stars_balance')

    with op.batch_alter_table('revenue_transactions', schema=None) as batch_op:
        batch_op.drop_column('telegram_charge_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_column('is_read')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
