"""add_onboarding_completed_steps

Revision ID: 4599ca70e57a
Revises: f05645d86065
Create Date: 2026-02-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import json


# revision identifiers, used by Alembic.
revision: str = '4599ca70e57a'
down_revision: Union[str, None] = 'f05645d86065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed_steps', sa.JSON(), nullable=True, comment='Tracks which onboarding steps user has completed'))

    # Set default values for existing users
    default_steps = json.dumps({
        "interactive_tour_completed": False,
        "first_swipe_done": False,
        "first_filter_opened": False,
        "first_superlike_used": False,
        "first_chat_opened": False,
        "first_voice_message_sent": False,
        "first_match_achieved": False,
        "profile_completion_prompted": False
    })
    # Escape single quotes for SQL (SQLite/PostgreSQL compatible)
    escaped_steps = default_steps.replace("'", "''")
    op.execute(
        f"UPDATE users SET onboarding_completed_steps = '{escaped_steps}' WHERE onboarding_completed_steps IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed_steps')
    # ### end Alembic commands ###
