"""add_push_subscriptions

Revision ID: bfa2729b3e19
Revises: d34c87028925
Create Date: 2026-01-09 23:11:33.906891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa2729b3e19'
down_revision: Union[str, None] = 'd34c87028925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint'), ['endpoint'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True, comment='Height in cm (150-220)'))
        batch_op.add_column(sa.Column('smoking', sa.String(length=20), nullable=True, comment='never, sometimes, regularly'))
        batch_op.add_column(sa.Column('drinking', sa.String(length=20), nullable=True, comment='never, socially, regularly'))
        batch_op.add_column(sa.Column('education', sa.String(length=50), nullable=True, comment='high_school, bachelor, master, phd'))
        batch_op.add_column(sa.Column('looking_for', sa.String(length=30), nullable=True, comment='relationship, friendship, casual, not_sure'))
        batch_op.add_column(sa.Column('children', sa.String(length=30), nullable=True, comment='have, want, dont_want, maybe'))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_selfie', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_selfie')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('children')
        batch_op.drop_column('looking_for')
        batch_op.drop_column('education')
        batch_op.drop_column('drinking')
        batch_op.drop_column('smoking')
        batch_op.drop_column('height')

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint'))

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
