"""add_missing_user_columns

Revision ID: de04cc0a8fee
Revises: 84c234c1a660
Create Date: 2026-01-11 11:20:58.989426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de04cc0a8fee'
down_revision: Union[str, None] = '84c234c1a660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
