"""add_ux_preferences_to_user

Revision ID: f05645d86065
Revises: 11efbc24f179
Create Date: 2026-02-05 08:01:42.327679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05645d86065'
down_revision: Union[str, None] = '11efbc24f179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ux_preferences', sa.JSON(), nullable=True, comment='User UX preferences for sounds, haptics, animations'))

    # Set default values for existing users
    op.execute("UPDATE users SET ux_preferences = '{\"sounds_enabled\": true, \"haptic_enabled\": true, \"reduced_motion\": false}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ux_preferences')

    # ### end Alembic commands ###
