"""Sync_schema

Revision ID: 1de50891d900
Revises: 87d9bd3d0c22
Create Date: 2026-01-10 22:24:45.610487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de50891d900'
down_revision: Union[str, None] = '87d9bd3d0c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to users table
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='active, suspended, banned, pending'))
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=20), server_default='free', nullable=False, comment='free, gold, platinum'))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False, comment='user, admin, moderator'))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True, comment="User's city for display"))
    op.add_column('users', sa.Column('location', sa.String(length=200), nullable=True, comment="User's full location string"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'city')
    op.drop_column('users', 'role')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
