"""use_enums_for_user_model

Revision ID: 6ee0b7a507b9
Revises: 0ad35de095ed
Create Date: 2026-01-12 07:51:54.957298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee0b7a507b9'
down_revision: Union[str, None] = '0ad35de095ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', 'PENDING', name='userstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FREE', 'GOLD', 'PLATINUM', name='subscriptiontier'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('subscription_tier',
               existing_type=sa.Enum('FREE', 'GOLD', 'PLATINUM', name='subscriptiontier'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', 'PENDING', name='userstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
