"""admin_dashboard_perfect_tables

Revision ID: 87d9bd3d0c22
Revises: 172dcbf0aea7
Create Date: 2026-01-10 13:22:44.070967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d9bd3d0c22'
down_revision: Union[str, None] = '172dcbf0aea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_resource', sa.String(length=100), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('backup_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_metrics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_metrics_metric_name'), ['metric_name'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('whitelist_users', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_key'), ['key'], unique=True)

    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('target_segment', sa.JSON(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nsfw_detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('top_label', sa.String(length=50), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_cohorts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_date', sa.Date(), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('retention_data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_cohorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_cohorts_cohort_date'), ['cohort_date'], unique=False)

    op.create_table('security_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_scores_user_id'), ['user_id'], unique=True)

    op.create_table('moderation_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=100), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notes_user_id'), ['user_id'], unique=False)

    op.create_table('user_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('segment_name', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_segments_user_id'), ['user_id'], unique=False)

    op.create_table('verification_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('submitted_photos', sa.JSON(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_requests_user_id'), ['user_id'], unique=False)

    op.create_table('appeals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ban_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ban_id'], ['banned_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeals')
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_requests_user_id'))

    op.drop_table('verification_requests')
    with op.batch_alter_table('user_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_segments_user_id'))

    op.drop_table('user_segments')
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notes_user_id'))

    op.drop_table('user_notes')
    op.drop_table('push_campaigns')
    op.drop_table('moderation_queue')
    with op.batch_alter_table('fraud_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_scores_user_id'))

    op.drop_table('fraud_scores')
    op.drop_table('email_campaigns')
    op.drop_table('security_alerts')
    with op.batch_alter_table('retention_cohorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_cohorts_cohort_date'))

    op.drop_table('retention_cohorts')
    op.drop_table('nsfw_detections')
    op.drop_table('marketing_campaigns')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_key'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_metrics_metric_name'))
        batch_op.drop_index(batch_op.f('ix_daily_metrics_date'))

    op.drop_table('daily_metrics')
    op.drop_table('backup_status')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_name'))

    op.drop_table('analytics_events')
    # ### end Alembic commands ###
