"""Add advanced analytics models

Revision ID: a5d0774ffce9
Revises: e1a2b3c4d5e6
Create Date: 2026-01-10 12:07:38.656940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a5d0774ffce9'
down_revision: Union[str, None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_stats_date'), ['date'], unique=False)

    op.create_table('translation_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_keys_key'), ['key'], unique=True)

    op.create_table('web_vital_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_vital_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_vital_logs_path'), ['path'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocks_blocker_id'), ['blocker_id'], unique=False)

    op.create_table('likes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('liker_id', sa.Uuid(), nullable=False),
    sa.Column('liked_id', sa.Uuid(), nullable=False),
    sa.Column('is_super', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['liked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_liked_id'), ['liked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_liker_id'), ['liker_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reported_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reported_id'), ['reported_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)

    op.create_table('translation_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['translation_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_values_language_code'), ['language_code'], unique=False)

    op.create_table('wallet_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('algorithm_settings', schema=None) as batch_op:
        batch_op.alter_column('weights',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('experimental_flags',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('custom_reports', schema=None) as batch_op:
        batch_op.alter_column('configuration',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('icebreakers', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active', comment='active, suspended, banned, pending'))
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='free', comment='free, gold, platinum'))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user', comment='user, admin, moderator'))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True, comment="User's city for display"))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True, comment="User's full location string"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('city')
        batch_op.drop_column('role')
        batch_op.drop_column('subscription_tier')
        batch_op.drop_column('status')

    with op.batch_alter_table('icebreakers', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('custom_reports', schema=None) as batch_op:
        batch_op.alter_column('configuration',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('algorithm_settings', schema=None) as batch_op:
        batch_op.alter_column('experimental_flags',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('weights',
               existing_type=sqlite.JSON(),
               nullable=True)

    op.drop_table('wallet_connections')
    with op.batch_alter_table('translation_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_values_language_code'))

    op.drop_table('translation_values')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_reported_id'))

    op.drop_table('reports')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_liker_id'))
        batch_op.drop_index(batch_op.f('ix_likes_liked_id'))

    op.drop_table('likes')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_blocks_blocked_id'))

    op.drop_table('blocks')
    with op.batch_alter_table('web_vital_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_vital_logs_path'))

    op.drop_table('web_vital_logs')
    with op.batch_alter_table('translation_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_keys_key'))

    op.drop_table('translation_keys')
    with op.batch_alter_table('system_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_stats_date'))

    op.drop_table('system_stats')
    # ### end Alembic commands ###
