"""Add call and metric models

Revision ID: b823a7011a7e
Revises: a5d0774ffce9
Create Date: 2026-01-10 12:14:07.195160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b823a7011a7e'
down_revision: Union[str, None] = 'a5d0774ffce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('wcag_level', sa.String(length=10), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('ndcg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('initiator_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('call_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_sessions')
    op.drop_table('recommendation_metrics')
    op.drop_table('accessibility_reports')
    # ### end Alembic commands ###
